name: Restarts the server
on:
  workflow_call:
  workflow_dispatch:
jobs:
  restart:
    name: ðŸ”¨ Restart
    runs-on: ubuntu-latest
    container:
      image: alexanderbifulco/dayz-restart
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        SERVICE_ID: ${{ secrets.SERVICE_ID }}
    steps:
      - run: "restart"