name: Server configuration changes
on:
  push:
    branches: [ master ]
    paths:
      - "dayzps_missions/**"
  workflow_dispatch:
jobs:
  deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
  restart:
    needs: deploy
    name: ðŸ”¨ Restart
    runs-on: ubuntu-latest
    container:
      image: alexanderbifulco/dayz-restart
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        SERVICE_ID: ${{ secrets.SERVICE_ID }}
    steps:
      - run: "restart"
